// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package education_person_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EducationPersonApiServiceClient is the client API for EducationPersonApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationPersonApiServiceClient interface {
	// DescribePersonV1 - Describe a person
	DescribePersonV1(ctx context.Context, in *DescribePersonV1Request, opts ...grpc.CallOption) (*DescribePersonV1Response, error)
}

type educationPersonApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationPersonApiServiceClient(cc grpc.ClientConnInterface) EducationPersonApiServiceClient {
	return &educationPersonApiServiceClient{cc}
}

func (c *educationPersonApiServiceClient) DescribePersonV1(ctx context.Context, in *DescribePersonV1Request, opts ...grpc.CallOption) (*DescribePersonV1Response, error) {
	out := new(DescribePersonV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.education_person_api.v1.EducationPersonApiService/DescribePersonV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationPersonApiServiceServer is the server API for EducationPersonApiService service.
// All implementations must embed UnimplementedEducationPersonApiServiceServer
// for forward compatibility
type EducationPersonApiServiceServer interface {
	// DescribePersonV1 - Describe a person
	DescribePersonV1(context.Context, *DescribePersonV1Request) (*DescribePersonV1Response, error)
	mustEmbedUnimplementedEducationPersonApiServiceServer()
}

// UnimplementedEducationPersonApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEducationPersonApiServiceServer struct {
}

func (UnimplementedEducationPersonApiServiceServer) DescribePersonV1(context.Context, *DescribePersonV1Request) (*DescribePersonV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribePersonV1 not implemented")
}
func (UnimplementedEducationPersonApiServiceServer) mustEmbedUnimplementedEducationPersonApiServiceServer() {
}

// UnsafeEducationPersonApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationPersonApiServiceServer will
// result in compilation errors.
type UnsafeEducationPersonApiServiceServer interface {
	mustEmbedUnimplementedEducationPersonApiServiceServer()
}

func RegisterEducationPersonApiServiceServer(s grpc.ServiceRegistrar, srv EducationPersonApiServiceServer) {
	s.RegisterService(&EducationPersonApiService_ServiceDesc, srv)
}

func _EducationPersonApiService_DescribePersonV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePersonV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationPersonApiServiceServer).DescribePersonV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.education_person_api.v1.EducationPersonApiService/DescribePersonV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationPersonApiServiceServer).DescribePersonV1(ctx, req.(*DescribePersonV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationPersonApiService_ServiceDesc is the grpc.ServiceDesc for EducationPersonApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationPersonApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.education_person_api.v1.EducationPersonApiService",
	HandlerType: (*EducationPersonApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribePersonV1",
			Handler:    _EducationPersonApiService_DescribePersonV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/education_person_api/v1/education_person_api.proto",
}
