# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/education_person_api/v1/education_person_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9ozonmp/education_person_api/v1/education_person_api.proto\x12\x1eozonmp.education_person_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n\x06Person\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n\x03\x66oo\x18\x02 \x01(\x04R\x03\x66oo\x12\x34\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"?\n\x17\x44\x65scribePersonV1Request\x12$\n\tperson_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x08personId\"X\n\x18\x44\x65scribePersonV1Response\x12<\n\x05value\x18\x01 \x01(\x0b\x32&.ozonmp.education_person_api.v1.PersonR\x05value2\xc6\x01\n\x19\x45\x64ucationPersonApiService\x12\xa8\x01\n\x10\x44\x65scribePersonV1\x12\x37.ozonmp.education_person_api.v1.DescribePersonV1Request\x1a\x38.ozonmp.education_person_api.v1.DescribePersonV1Response\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/templates/{person_id}B^Z\\github.com/aaa2ppp/ozonmp-education-person-api/pkg/education-person-api;education_person_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ozonmp.education_person_api.v1.education_person_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\\github.com/aaa2ppp/ozonmp-education-person-api/pkg/education-person-api;education_person_api'
  _DESCRIBEPERSONV1REQUEST.fields_by_name['person_id']._options = None
  _DESCRIBEPERSONV1REQUEST.fields_by_name['person_id']._serialized_options = b'\372B\0042\002 \000'
  _EDUCATIONPERSONAPISERVICE.methods_by_name['DescribePersonV1']._options = None
  _EDUCATIONPERSONAPISERVICE.methods_by_name['DescribePersonV1']._serialized_options = b'\202\323\344\223\002\033\022\031/v1/templates/{person_id}'
  _globals['_PERSON']._serialized_start=181
  _globals['_PERSON']._serialized_end=277
  _globals['_DESCRIBEPERSONV1REQUEST']._serialized_start=279
  _globals['_DESCRIBEPERSONV1REQUEST']._serialized_end=342
  _globals['_DESCRIBEPERSONV1RESPONSE']._serialized_start=344
  _globals['_DESCRIBEPERSONV1RESPONSE']._serialized_end=432
  _globals['_EDUCATIONPERSONAPISERVICE']._serialized_start=435
  _globals['_EDUCATIONPERSONAPISERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
